### ISSUE TITLE
summoning stops working

### ISSUE THREAD

**Issue by Latravant** [smd111/Gearswap-Skillup#11]
summoning magic stops working sometimes and i think i found out why but dont know how to fix it. i noticed when my toon ran out of mp after it cast a summon spell, the lua still tried to use /ja "release" then it just stopped working since there was nothing to release.

**Comment by madantichris** [comment]
I found this issue as well.  The script will fail if you run out of MP between the summon and the release and the avatar fades away on its own.  I fixed it in my local copy.  I will have to see if I can do a pull request to get the fix up here.

**Comment by gh0sth4ck3d** [comment]
@madantichris would it be possible to get your fix for this? I am having the same issue.

**Comment by madantichris** [comment]
> @madantichris would it be possible to get your fix for this? I am having the same issue.

I will get my pull request in tonight if possible.  If the project owner isn't responsive or interested in maintaining it, I'll fork it.

**Comment by madantichris** [comment]
@Latravant @gh0sth4ck3d Please pull down the latest script and give it a try.  @smd111 has merged my fix into the master branch.

**Comment by gh0sth4ck3d** [comment]
@madantichris thanks man, will give it a go.

**Comment by wezzie88** [comment]
@madantichris @smd111 i know you guys said you dont want to know if issues are found but, im having one and cant find a way to make it work, im casting summoning and its not releasing after the first cast, is there a timer somewhere to increase cause it automatically goes into /Heal mode

Thanks
