### ISSUE TITLE
Auto Rest?

### ISSUE THREAD

**Issue by vleango** [smd111/Gearswap-Skillup#2]
Hello, just wondering if the script supports auto-rest? I tried the script and my character doesn't do it after depleting his MP. The only option I used was "Start Summoning Magic" from the menu.

Thank you.

**Comment by vleango** [comment]
Nevermind... I think my pointer was on the menu and that caused it to not work.

**Comment by smd111** [comment]
the only one i know of that has issues in healing when using blu

**Comment by vleango** [comment]
I found the cause of SMN not resting.

If the avatar is still out, and MP goes to 0, the avatar is desummoned on its own. The script tries to release it but the message "That action requires a pet" appears. Then the script breaks.

**Comment by smd111** [comment]
there is just one issue i cane reproduce it

**Comment by vleango** [comment]
How have you tried to reproduce it?
It occurs very often. Probably 1 out of every 3 times of summoning and resting.

If you run the script and when player's MP is out before the /release command is made then the error occurs and the script breaks.

**Comment by smd111** [comment]
by running each Healing/Geomancy/Enhancing/Ninjutsu/Singing/Blue/Summoning for an at lest an hour each the only one that has ever stopped on me was Blue and why that happened i dont know and have tried to figure it out for months

**Comment by smd111** [comment]
i just uploaded a new version please try it out

**Comment by vleango** [comment]
It now says
```
>> ja "Release" <me>
... A command error occurred.
```

**Comment by smd111** [comment]
just pushed another one try that

**Comment by vleango** [comment]
it's back to
```
That action requires a pet.
```

(after the avatar is released on its own since the character is out of MP

**Comment by smd111** [comment]
try the new one

**Comment by vleango** [comment]
It is constantly showing
```
Unable to cast spells at this time.
```
And it seems that `Use Geo's Refresh` breaks the script when an avatar is out.

After turning off Geo's Refresh, the /heal did seem to work though.
MP was running low, my character went to /heal mode while the avatar is out and the avatar released itself after MP was drained to zero.

**Comment by vleango** [comment]
After the full /heal, the message `Unable to cast spells at this time.` does not appear anymore.

**Comment by vleango** [comment]
The /heal looks good though.
Avatar was summoned. MP went to 0. Avatar released on its own. Character went to /heal.
I will leave my game on for the next 1/2 hour - 1 hour to see how it goes.
Thanks for your hard work.

**Comment by smd111** [comment]
always skill up with the job you want to skill as the main job
if you try to skill up smn with GEO/SMN you will get that error because GEO uses a pet and you can only have 1 pet

**Comment by vleango** [comment]
My job is SMN/GEO

**Comment by strevorrow** [comment]
This issue is still prominent and has consistently occurred when skilling up summoning magic and running out of MP.

**Comment by smd111** [comment]
the only thing i can find that causes this issue is packet drop
