### ISSUE TITLE
No text in the Window. Just the black background.

### ISSUE THREAD

**Issue by fireshot4302** [smd111/Gearswap-Skillup#3]
When launching the script it opens the textbox, but it is black no text is shown. The commands still work manually though.

**Comment by smd111** [comment]
try downloading this font and installing it
http://www.ufonts.com/download/segoe-ui-symbol/77998.html

**Comment by fireshot4302** [comment]
I already have that font installed. It used to work fine. I updated the lua file and now it doesn't work anymore.

**Comment by smd111** [comment]
any errors??

**Comment by fireshot4302** [comment]
The new version is working.

Thanks!

**Comment by smd111** [comment]
np
