### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by justinmd1911** [smd111/Gearswap-Skillup#6]
I am new to this gearswap, so please bear with me. I have downloaded the skillup lua file, and copied it to the data folder. When i attempt to load the file, it states GearSwap: Command not found. I was curious if i have to place the file someplace else to be recognized?

**Comment by smd111** [comment]
the correct command is(you should be able to copy past it in to your windower command line)
gs l skillup.lua
l = small L
i prefer to put my files in to
gearswap/data/<charname>
so for you (using your github name seance i dont want or need to know your ffxi char name)
gearswap/data/justinmd1911
but it should work from
gearswap/data

**Comment by justinmd1911** [comment]
Awesome, seems that the l = small L i mistook for a 1. I appreciate the quick response as well.

**Comment by justinmd1911** [comment]
Working like a champ now!

**Comment by smd111** [comment]
ok have fun with it
