### ISSUE TITLE
WHM Enhancing Skillup

### ISSUE THREAD

**Issue by Ledicious** [smd111/Gearswap-Skillup#8]
The script is casting Recall spells as part of enhancing skillups.  Is there a way to blacklist spells or specify only the spells you want to cast?

**Comment by smd111** [comment]
i cant believe over a year and your the first to let me know that it still tried to use Recall spells thank you so much

there is no black list but you select your own spells and thats what the USER IN CODE SETTINGS section is for as long as thay follow the rule of casting on self only and not in battle


it has been updated for Recall spells
